name: flutter_ui_food_delivery_app
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.2.0-122.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  lottie: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/images/
    - assets/anim/
    - assets/icons/
    - assets/fonts/
    - assets/images/foods/

  fonts:
    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf

  uses-material-design: true
